"""
Django settings for mequedo_ai project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Lee la clave secreta desde las variables de entorno de Railway.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'una-clave-secreta-de-desarrollo-insegura')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG se deshabilita en producción por defecto.
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Railway proporciona la URL pública en una variable de entorno.
# También puedes añadir 'localhost' y '127.0.0.1' para desarrollo local.
RAILWAY_URL = os.getenv('RAILWAY_STATIC_URL')
ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1',
    'ai-api.mequedo.app', # Tu nuevo subdominio para la IA
]
if RAILWAY_URL:
    # Añadimos el dominio de Railway para las comprobaciones de salud de la plataforma
    ALLOWED_HOSTS.append(RAILWAY_URL) 

# Es buena práctica confiar en el dominio de despliegue para evitar problemas de CSRF.
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000', # URL de tu frontend Next.js en desarrollo
    'http://127.0.0.1:3000',
    'https://mequedo.app', # Tu dominio principal del frontend
    'https://www.mequedo.app', # Tu dominio con www
]
if RAILWAY_URL:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RAILWAY_URL}') # Para las comprobaciones de salud

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders', # Añadir corsheaders
    'rest_framework',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware', # Desactivado temporalmente
    'corsheaders.middleware.CorsMiddleware', # Añadir middleware de CORS
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- Configuración de CORS ---
# Permitir que cualquier dominio se conecte. Para mayor seguridad, puedes reemplazar '*'
# con la URL de tu frontend (ej: 'https://mi-frontend.up.railway.app')
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'mequedo_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mequedo_ai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
